# Configurazione per ReWTSE-LLM-RL con DeepSeek

# Ticker stocks da tradare
tickers:
  - AAPL
  - AMZN
  - GOOGL
  - META
  - MSFT
  - TSLA

# Date range per i dati
data:
  start_date: "2012-01-01"
  end_date: "2020-12-31"

# Configurazione LLM (DeepSeek)
llm:
  llm_model: "deepseek-chat"  # DeepSeek-V3
  temperature: 0.0
  deepseek_api_key: "${DEEPSEEK_API_KEY}"

# Configurazione ReWTSE (Ottimizzata per DeepSeek)
rewts:
  chunk_length: 400  # ~2 trading years
  lookback_length: 200  # ~1 trading year
  forecast_horizon: 1
  episodes_per_chunk: 100

  # DDQN hyperparameters (ottimizzati)
  gamma: 0.995
  epsilon_start: 1.0
  epsilon_min: 0.05
  epsilon_decay: 0.998
  learning_rate: 0.0005  # 5e-4
  batch_size: 128
  buffer_size: 50000
  target_update_freq: 20
  hidden_dims:
    - 256
    - 256
    - 128

# Configurazione Trading Environment
trading_env:
  initial_balance: 10000
  transaction_cost: 0.0015  # 0.15%
  max_position: 0.95  # Max 95% capital in position
  max_drawdown_limit: 0.15  # Stop trading at 15% drawdown

# Strategia LLM frequency
strategy_frequency: 20  # Strategia ogni 20 giorni di trading

# Parallel execution settings
parallel_workers: 8  # Numero di workers paralleli per LLM
max_requests_per_second: 8.0  # 8 req/s per DeepSeek API
skip_news_processing: false  # News processing abilitato
