# Configurazione per ReWTSE-LLM-RL

# Ticker stocks da tradare
tickers:
  - AAPL
  - AMZN
  - GOOGL
  - META
  - MSFT
  - TSLA

# Date range per i dati
data:
  start_date: "2012-01-01"
  end_date: "2024-12-31"

# Configurazione LLM (Google Gemini)
llm:
  llm_model: "gemini-2.5-flash"  # Gemini 2.5 Flash
  temperature: 0.0
  seed: 49
  gemini_api_key: ${GEMINI_API_KEY}  # Da environment variable
  project_id: "rewts-quant-trading"  # GCP project ID per paid tier quota

# Configurazione ReWTSE
rewts:
  chunk_length: 2016  # 14 giorni di trading
  lookback_length: 432  # 3 giorni di trading
  forecast_horizon: 1
  episodes_per_chunk: 50

  # DDQN hyperparameters
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_min: 0.01
  epsilon_decay: 0.995
  learning_rate: 0.001
  batch_size: 64
  buffer_size: 10000
  target_update_freq: 10
  hidden_dims:
    - 128
    - 64

# Configurazione Trading Environment
trading_env:
  initial_balance: 10000
  transaction_cost: 0.001  # 0.1%
  max_position: 1.0  # No leverage

# Strategia LLM frequency
strategy_frequency: 25  # Strategia mensile (~25 trading days, ridotto del 20%)

# Parallel execution settings
# PAID TIER: 1000 RPM limit - optimized for speed
parallel_workers: 8  # Numero di workers paralleli
max_requests_per_second: 8.0  # 8 req/s = 480 RPM (safe margin under 1000 RPM limit)
skip_news_processing: false  # News processing enabled (full strategy quality)
